input_stream: "input_video"
input_side_packet: "texture_3d"
input_side_packet: "asset_3d"
output_stream: "output_video"

# node: {
#     calculator: "TriangleShaderCalculator"
#     input_stream: "VIDEO:input_video"
#     output_stream: "output_video"
# }

node: {
    calculator: "OpenGlShaderCalculator"
    input_stream: "VIDEO:input_video"
    output_stream: "output_video"
}
