licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "triangle_renderer",
    srcs = ["triangle_renderer.cc"],
    hdrs = ["triangle_renderer.h"],
    deps = [
        # ":mesh_3d_utils",
        # ":validation_utils",
        # "//mediapipe/framework/formats:image_format_cc_proto",
        # "//mediapipe/framework/formats:image_frame",
        # "//mediapipe/framework/formats:matrix_data_cc_proto",
        # "//mediapipe/framework/port:ret_check",
        # "//mediapipe/framework/port:status",
        # "//mediapipe/framework/port:statusor",
        # "//mediapipe/gpu:gl_base",
        # "//mediapipe/gpu:shader_util",
        # "//mediapipe/modules/face_geometry/protos:environment_cc_proto",
        # "//mediapipe/modules/face_geometry/protos:face_geometry_cc_proto",
        # "//mediapipe/modules/face_geometry/protos:mesh_3d_cc_proto",
        "@com_google_absl//absl/memory",
        "@com_google_absl//absl/types:optional",
    ],
)
